name: jungle
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  page_transition: ^2.0.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  path_provider: ^2.0.12
  url_launcher: ^6.1.9
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - asset/image/notes.png
    - asset/image/notes-amico.png
    - asset/image/notes-pana.png
    - asset/image/notes-rafiki.png

  fonts:
    - family: Lato
      fonts:
        - asset: asset/font/Lato-Regular.ttf
