name: jungle
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  path_provider: ^2.0.12
  url_launcher: ^6.1.9
  intl: ^0.18.1
  flutter_native_splash: ^2.3.1
  get: ^4.6.5
  google_fonts: ^5.1.0
  smooth_page_indicator: ^1.1.0
  jiffy: ^6.2.1
  flutter_launcher_icons: ^0.13.1
  awesome_notifications: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - asset/image/1st_page.png
    - asset/image/2nd_page.png
    - asset/image/3rd_page.png
    - asset/image/complete_image.png
    - asset/image/notification_image.png
    - asset/image/task_image.png
  
  fonts:
    - family: Regular
      fonts:
        - asset: "asset/font/Lato-Regular.ttf"

flutter_native_splash:
  color: "#009688"

  android_12:
    color: "#009688"
    icon_background_color: "#009688"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "asset/icon/app_icon.png"
  adaptive_icon_background: "asset/icon/app_icon_background.png"
  adaptive_icon_foreground: "asset/icon/app_icon_foreground.png"
